[package]
name = "rust-way-of-life"
version = "0.1.0"
authors = ["haja <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_xoshiro = "0.6.0"
