use std::thread;
use std::time::Duration;

use rust_way_of_life::Game;

fn main() {
  //let mut game = Game::new(100, 10, 1234);
  let mut game = Game::from_specific("\
...........................
...........................
...........................
...........................
..............###..........
................#..........
...............#...........
...........................
...........................
...........................
...........................
...........................",
                                     false,
  );

  loop {
    print(&game);
    game = game.tick();
    thread::sleep(Duration::from_millis(100));
  }
}

fn print(game: &Game) {
  println!("{}", game);
}
